spring:
  application:
    name: rest-api-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
      show-sql: false
    open-in-view: false